### ISSUE TITLE
Potential GPL2 concern

### ISSUE THREAD

**Issue by AkihiroSuda** [afbjorklund/lima-gui#1]
Thanks a lot for working on this, but I'm not sure this project can be licensed under the terms of [3-clause BSDL](https://github.com/afbjorklund/lima-gui/blob/2a8df51242b321b2630084b4e10b6a8a4cd11edc/LICENSE), as it seems [linked with `qtermwidget`](https://github.com/afbjorklund/lima-gui/blob/2a8df51242b321b2630084b4e10b6a8a4cd11edc/systray.pro#L17), which seems licensed under the terms of GPL2 https://github.com/lxqt/qtermwidget/tree/0.17.0#overview

**Comment by afbjorklund** [comment]
Fixed in ef226bb7dcd7a99cff94ecd0a318e8a9432638d7
