### ISSUE TITLE
lima-gui cannot find limactl installed by macports

### ISSUE THREAD

**Issue by hiroaki-ishikawa** [afbjorklund/lima-gui#15]
Hello,
I installed lima by macports. Then limactl is located /opt/local/bin/limactl but lima-gui couldn't find this.

Thank you!

<img width="532" alt="スクリーンショット 2022-04-26 2 55 35" src="https://user-images.githubusercontent.com/8679609/165146452-ee521fda-90e1-440e-af9e-8d31e0c09fc6.png">

**Comment by afbjorklund** [comment]
Do people still use MacPorts ?

Anyway, the paths are hardcoded
