### ISSUE TITLE
starts but doesn't do anything

### ISSUE THREAD

**Issue by hemna** [afbjorklund/lima-gui#4]
I built this on my mac.  It seems to run ok, but doesn't show the existing lima vms I have already running.
I also tried to create a vm with it, and nothing happens.

**Comment by afbjorklund** [comment]
I didn't add so much debugging logs to the app, but this is the command being run: `limactl list --json`

It is Qt doing the PATH handling, but should be "normal". Can you check the About box title (version) ?

**Comment by hemna** [comment]
![Screen Shot 2022-01-31 at 12 36 06 PM](https://user-images.githubusercontent.com/672207/151844076-815cd5fb-484e-43a1-967b-13849e6c7e62.png)

**Comment by afbjorklund** [comment]
Ok, so path didn't help.

Where is "limactl" ? `/usr/local/bin` ?

**Comment by hemna** [comment]
```
└─> which limactl
/usr/local/bin/limactl
```

**Comment by afbjorklund** [comment]
I could reproduce the empty list by removing `limactl`.

Making it a fatal error for now, if it can't be found in PATH.

**Comment by hemna** [comment]
![Screen Shot 2022-01-31 at 1 38 12 PM](https://user-images.githubusercontent.com/672207/151852801-686f40c6-99eb-4954-b9eb-efcd3aa2fcda.png)


Yes I get this now.

**Comment by afbjorklund** [comment]
I suppose that is "progress". Now, how to debug QStandardPaths

https://doc.qt.io/qt-5/qstandardpaths.html#findExecutable

> On most operating systems the system path is determined by the PATH environment variable.

And I assume that `/usr/local/bin` is in there, somewhere ?

----

Igoring this decade-only GNU vs BSD debate on _where_ in the path.

**Comment by afbjorklund** [comment]
@hemna 
Hardcoded the standard Brew paths now, hopefully that fixes it ?

**Comment by afbjorklund** [comment]
Now fixed, both for list and for start. Hardcoded brew paths, for now.
